Main svc
grand1964/java-explore-with-me pull request #6
Opened 2023-10-21 20:06 UTC by grand1964

2023-10-22 20:35 UTC, NikolaiDem requested changes

2023-10-23 06:31 UTC, grand1964 commented on main/src/main/java/ru/practicum/ewm/controller/admin_api/AdminCategoryController.java
> +package ru.practicum.ewm.controller.admin_api;
private и public использовать нельзя, я потому и писал с подчеркиванием. Тогда я напишу priv и pub (тоже не очень красиво), а api вообще уберу

2023-10-23 07:18 UTC, grand1964 commented on main/src/main/java/ru/practicum/ewm/user/service/UserService.java
> +    List<UserDto> getUsers(Long[] ids, Pageable pageable);
В контроллер приходит именно массив, так требуют спецификации. Там же придется преобразовать его в список. Хорошо, сделаю, хотя смысл не очень понимаю.

2023-10-23 09:37 UTC, grand1964 commented on main/src/main/java/ru/practicum/ewm/compilation/service/CompilationServiceImpl.java
> +        Set<Event> events = eventRepository.findByIdIn(eventIds);
Метод getEventsFromIds требует список, а у нас множество.

2023-10-23 11:11 UTC, grand1964 commented on main/src/main/java/ru/practicum/ewm/event/model/Event.java
> +    private Long confirmedRequests;
Николай, тут я не согласен. Есть два способа проектирования: считать число подтвержденных заявок "на лету" или хранить их в базе. Какой способ лучше? В плане памяти - первый: не надо хранить лишнее поле. В плане производительности - второй: проще сохранить одно событие, чем заставлять базу просматривать все реквесты (их может быть много). Предлагаю оставить как есть. Я могу сделать то, что ты предлагаешь, но надо ли?

2023-10-24 00:44 UTC, NikolaiDem commented on main/src/main/java/ru/practicum/ewm/event/model/Event.java
> +    private Long confirmedRequests;
Event вовсе не знает ни о каких запросах, только запросы зависят от Event-а. Поэтому по логике  confirmedRequests быть здесь не должно. 
Даже если оставить это поле здесь, то у нас появляется 2 источника истины (это поле и сами исходные запросы), между которыми нужно постоянно поддерживать синхронизацию, а это дополнительные расходы.
Даже если мы хотим избавиться от просмотра всех реквестов при получении списка событий, то запоминать количество запросов лучше на уровне нового entity, которое предусмотрено именно для просмотров (так называемый паттерн CQRS).
Например, у нас очень много просмотров событий, в которые нужно добавить инфо о самом событии, количестве запросов, юзерах и много еще чего, тогда можем создать новую таблицу, которая будет являться таким большим агрегатом событий, реквестов, юзеров и т.д., и которая будет обновляться каждый раз, когда меняется событие, юзер, реквест и т.д. То есть пишем в одни таблицы, а читаем из других (из агрегированных). В этом случае можем потюнить производительность. 
Поэтому, если в нашем сервисе будет просмотров намного больше чем обновлений, то делать предварительные расчеты (confirmedRequests) логично при самом обновлении реквеста, да, но все же лучше не в этом энтити. А если такого требования у нас нет, то от поля confirmedRequests можно вовсе избавиться

2023-10-24 00:54 UTC, NikolaiDem commented on main/src/main/java/ru/practicum/ewm/compilation/service/CompilationServiceImpl.java
> +public class CompilationServiceImpl implements CompilationService {
Сделать модифицирующие методы транзакционными

2023-10-24 00:54 UTC, NikolaiDem commented on main/src/main/java/ru/practicum/ewm/compilation/service/CompilationServiceImpl.java
> +        Set<Event> events = eventRepository.findByIdIn(eventIds);
Значит, можно привести коллекции к единообразию

2023-10-24 01:00 UTC, NikolaiDem requested changes

2023-10-24 06:30 UTC, grand1964 commented on main/src/main/java/ru/practicum/ewm/controller/admin/user/AdminUserController.java
> +    public List<UserDto> getUsers(@RequestParam(required = false) Long[] ids,
В спецификациях в этом месте написано array[integer]. А где список - пишут List[...]. Давай не будем менять спецификации.

2023-10-26 21:08 UTC, NikolaiDem approved these changes

2023-10-27 07:00 UTC, merged